services:
  - type: web
    name: movie-recommender-backend
    env: python
    plan: free
    pythonVersion: "3.11.9"
    buildCommand:  python -m pip install --upgrade pip
      pip install --no-cache-dir -r requirements.txt
    startCommand:  gunicorn app:app --bind 0.0.0.0:$PORT --workers 4
    envVars:
      - key: DEBUG
        value: "false"
